use std::{env, fs, io::Write, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let days_dir = manifest_dir.join("src").join("days");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::create_dir_all(&out_dir).unwrap();

    let mut days: Vec<String> = fs::read_dir(&days_dir)
        .unwrap()
        .filter_map(|e| {
            let p = e.ok()?.path();
            (p.extension()?.to_str()? == "rs").then(|| {
                let stem = p.file_stem()?.to_str()?.to_string();
                (stem != "mod" && stem.starts_with("day_")).then_some(stem)
            })?
        })
        .collect();

    days.sort();
    let gen_path = out_dir.join("days_gen.rs");
    let mut f = fs::File::create(&gen_path).unwrap();

    writeln!(f, "// @generated by build.rs — do not edit").unwrap();

    for d in &days {
        writeln!(
            f,
            r#"pub mod {d} {{
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/days/{d}.rs"));
}}"#
        )
        .unwrap();
    }

    writeln!(f, "pub fn run_all() -> Vec<(usize, usize)> {{").unwrap();
    writeln!(f, "    let mut res: Vec<(usize, usize)> = Vec::new();").unwrap();
    for d in &days {
        writeln!(f, r#"    res.push(run_by_name("{d}"));"#).unwrap();
    }
    writeln!(f, "res").unwrap();
    writeln!(f, "}}").unwrap();

    writeln!(
        f,
        r#"
pub fn run_by_name(name: &str) -> (usize, usize) {{
    match name {{"#
    )
    .unwrap();
    for d in &days {
        let num = d.trim_start_matches("day_").parse::<usize>().unwrap();
        writeln!(f, r#"        "{d}" => {d}::run({num}),"#).unwrap();
    }
    writeln!(
        f,
        r#"        _ => (0,0),
    }}
}}"#
    )
    .unwrap();
}
